[package]
name = "bridge"
version = "0.0.1"
authors = ["mark.ts@blaize.tech", "tymofii.s@blaize.tech"]
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = "4.1.1"
near-contract-standards = "4.1.1"
serde = { version = "1.0" }
uint = { version = "0.8.3", default-features = false }
hex = "0.4.2"
ethabi = "12.0.0"
rlp = "0.4.2"
tiny-keccak = "1.4.0"
parse_duration = "2.1.1"
eth-types =  { git = "https://github.com/aurora-is-near/rainbow-bridge", rev = "3e859904f445105850c2a08b5a4b0fdc7680c841", default-features = false, features = ["eip1559"] }
spectre-bridge-common = { git = "ssh://git@github.com/aurora-is-near/spectre-bridge-common.git", rev = "8f98314ee9d7627a429fbc2ab4c5a59d98d4c2d9" }
