[package]
name = "utiles"
version = "0.1.0"
edition = "2021"

[dependencies]
near-sdk = "4.1.1"
serde_json = "1.0.91"
clap = { version = "4.1.4", features = ["derive"] }
fast-bridge-common = { git = "https://github.com/aurora-is-near/fast-bridge-common.git", tag = "0.1.2" }