[package]
name = "eth_types"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = "1.0.144"
near-sdk = "4.0.0"
borsh = "0.9.3"
rlp = "0.4.2"
rlp-derive = "0.1.0"
ethereum-types = "0.9.2"
derive_more = "0.99.17"

[features]
eip1559 = []
