[package]
name = "mock_ft_receiver"
version = "0.0.1"
authors = ["karim@aurora.dev"]
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = "4.1.1"
near-contract-standards = "4.1.1"
