name: fast-bridge-protocol build contracts

on:
  push:
  pull_request:
    branches: ["!main"]
  workflow_dispatch:

jobs:
  build_rust_contracts:
    runs-on: [self-hosted, light]
    steps:
      - uses: actions/checkout@v3
      - run: cd near; mkdir res; ./build.sh
      - run: |
          changed_files=$(git status --porcelain --untracked-files=no | wc -l);
          if [ $changed_files -gt 0 ]; then
          echo 'contract changed, please rebuild contract'
          exit 1
          fi
