name: spectre-bridge-protocol test automatically

on:
  push:
  pull_request:
    branches: ["!main"]
  workflow_dispatch:

jobs:
  test-cargo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          #ssh-key: ${{ secrets.submodulessh }}
          ssh-key: ${{ secrets.SSH_PRIV }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args:  --manifest-path ./near/contracts/Cargo.toml --all -- --check
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args:  --manifest-path ./near/contracts/Cargo.toml -- -A clippy::too-many-arguments -D warnings
      - run: cd near; mkdir res; ./build.sh
      - run: cd near; ./test.sh
      
  test-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: cd eth; npm install; npm install -g ganache-cli
      - run: cd eth; WEB3_INFURA_PROJECT_ID=${{secrets.WEB3_INFURA_PROJECT_ID}} npm run test:mainnet-fork
